version: '3.8'
services:

  api:
    image: apiopensearch
    build: .
    ports:
      - "8080:8080"
    volumes:
        - .:/app
    env_file:
      - .env
    depends_on:
        - db
        - opensearch

  db:
    image: postgres:latest
    ports:
      -  "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data  # Use a named volume

  opensearch:
    image: opensearchproject/opensearch:latest
    env_file:
      - .env
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - opensearch_data:/usr/share/elasticsearch/data  # Use a named volume


volumes:
  db_data:  # Define named volume for PostgreSQL
  opensearch_data:  # Define named volume for OpenSearch