version: '3.8'
services:

  api:
    image: apiopensearch
    build: .
    ports:
      - "8080:8080"
    volumes:
        - .:/app
    env_file:
      - .env
    depends_on:
        - db
        - opensearch

  db:
    image: postgres:latest
    ports:
      -  "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data  # Use a named volume

  opensearch:
    image: opensearchproject/opensearch:2.6.0
    env_file:
      - .env
    environment:
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - opensearch_data:/usr/share/elasticsearch/data  # Use a named volume
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'green'" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:  # Define named volume for PostgreSQL
  opensearch_data:  # Define named volume for OpenSearch